// Code generated by counterfeiter. DO NOT EDIT.
package fake

import (
	"sync"
	"time"

	"code.cloudfoundry.org/korifi/api/presenter"
	"code.cloudfoundry.org/korifi/api/repositories"
)

type RecordWithLastOperation struct {
	GetCreatedAtStub        func() time.Time
	getCreatedAtMutex       sync.RWMutex
	getCreatedAtArgsForCall []struct {
	}
	getCreatedAtReturns struct {
		result1 time.Time
	}
	getCreatedAtReturnsOnCall map[int]struct {
		result1 time.Time
	}
	GetDeletedAtStub        func() *time.Time
	getDeletedAtMutex       sync.RWMutex
	getDeletedAtArgsForCall []struct {
	}
	getDeletedAtReturns struct {
		result1 *time.Time
	}
	getDeletedAtReturnsOnCall map[int]struct {
		result1 *time.Time
	}
	GetStateStub        func() repositories.RecordState
	getStateMutex       sync.RWMutex
	getStateArgsForCall []struct {
	}
	getStateReturns struct {
		result1 repositories.RecordState
	}
	getStateReturnsOnCall map[int]struct {
		result1 repositories.RecordState
	}
	GetUpdatedAtStub        func() *time.Time
	getUpdatedAtMutex       sync.RWMutex
	getUpdatedAtArgsForCall []struct {
	}
	getUpdatedAtReturns struct {
		result1 *time.Time
	}
	getUpdatedAtReturnsOnCall map[int]struct {
		result1 *time.Time
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *RecordWithLastOperation) GetCreatedAt() time.Time {
	fake.getCreatedAtMutex.Lock()
	ret, specificReturn := fake.getCreatedAtReturnsOnCall[len(fake.getCreatedAtArgsForCall)]
	fake.getCreatedAtArgsForCall = append(fake.getCreatedAtArgsForCall, struct {
	}{})
	stub := fake.GetCreatedAtStub
	fakeReturns := fake.getCreatedAtReturns
	fake.recordInvocation("GetCreatedAt", []interface{}{})
	fake.getCreatedAtMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *RecordWithLastOperation) GetCreatedAtCallCount() int {
	fake.getCreatedAtMutex.RLock()
	defer fake.getCreatedAtMutex.RUnlock()
	return len(fake.getCreatedAtArgsForCall)
}

func (fake *RecordWithLastOperation) GetCreatedAtCalls(stub func() time.Time) {
	fake.getCreatedAtMutex.Lock()
	defer fake.getCreatedAtMutex.Unlock()
	fake.GetCreatedAtStub = stub
}

func (fake *RecordWithLastOperation) GetCreatedAtReturns(result1 time.Time) {
	fake.getCreatedAtMutex.Lock()
	defer fake.getCreatedAtMutex.Unlock()
	fake.GetCreatedAtStub = nil
	fake.getCreatedAtReturns = struct {
		result1 time.Time
	}{result1}
}

func (fake *RecordWithLastOperation) GetCreatedAtReturnsOnCall(i int, result1 time.Time) {
	fake.getCreatedAtMutex.Lock()
	defer fake.getCreatedAtMutex.Unlock()
	fake.GetCreatedAtStub = nil
	if fake.getCreatedAtReturnsOnCall == nil {
		fake.getCreatedAtReturnsOnCall = make(map[int]struct {
			result1 time.Time
		})
	}
	fake.getCreatedAtReturnsOnCall[i] = struct {
		result1 time.Time
	}{result1}
}

func (fake *RecordWithLastOperation) GetDeletedAt() *time.Time {
	fake.getDeletedAtMutex.Lock()
	ret, specificReturn := fake.getDeletedAtReturnsOnCall[len(fake.getDeletedAtArgsForCall)]
	fake.getDeletedAtArgsForCall = append(fake.getDeletedAtArgsForCall, struct {
	}{})
	stub := fake.GetDeletedAtStub
	fakeReturns := fake.getDeletedAtReturns
	fake.recordInvocation("GetDeletedAt", []interface{}{})
	fake.getDeletedAtMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *RecordWithLastOperation) GetDeletedAtCallCount() int {
	fake.getDeletedAtMutex.RLock()
	defer fake.getDeletedAtMutex.RUnlock()
	return len(fake.getDeletedAtArgsForCall)
}

func (fake *RecordWithLastOperation) GetDeletedAtCalls(stub func() *time.Time) {
	fake.getDeletedAtMutex.Lock()
	defer fake.getDeletedAtMutex.Unlock()
	fake.GetDeletedAtStub = stub
}

func (fake *RecordWithLastOperation) GetDeletedAtReturns(result1 *time.Time) {
	fake.getDeletedAtMutex.Lock()
	defer fake.getDeletedAtMutex.Unlock()
	fake.GetDeletedAtStub = nil
	fake.getDeletedAtReturns = struct {
		result1 *time.Time
	}{result1}
}

func (fake *RecordWithLastOperation) GetDeletedAtReturnsOnCall(i int, result1 *time.Time) {
	fake.getDeletedAtMutex.Lock()
	defer fake.getDeletedAtMutex.Unlock()
	fake.GetDeletedAtStub = nil
	if fake.getDeletedAtReturnsOnCall == nil {
		fake.getDeletedAtReturnsOnCall = make(map[int]struct {
			result1 *time.Time
		})
	}
	fake.getDeletedAtReturnsOnCall[i] = struct {
		result1 *time.Time
	}{result1}
}

func (fake *RecordWithLastOperation) GetState() repositories.RecordState {
	fake.getStateMutex.Lock()
	ret, specificReturn := fake.getStateReturnsOnCall[len(fake.getStateArgsForCall)]
	fake.getStateArgsForCall = append(fake.getStateArgsForCall, struct {
	}{})
	stub := fake.GetStateStub
	fakeReturns := fake.getStateReturns
	fake.recordInvocation("GetState", []interface{}{})
	fake.getStateMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *RecordWithLastOperation) GetStateCallCount() int {
	fake.getStateMutex.RLock()
	defer fake.getStateMutex.RUnlock()
	return len(fake.getStateArgsForCall)
}

func (fake *RecordWithLastOperation) GetStateCalls(stub func() repositories.RecordState) {
	fake.getStateMutex.Lock()
	defer fake.getStateMutex.Unlock()
	fake.GetStateStub = stub
}

func (fake *RecordWithLastOperation) GetStateReturns(result1 repositories.RecordState) {
	fake.getStateMutex.Lock()
	defer fake.getStateMutex.Unlock()
	fake.GetStateStub = nil
	fake.getStateReturns = struct {
		result1 repositories.RecordState
	}{result1}
}

func (fake *RecordWithLastOperation) GetStateReturnsOnCall(i int, result1 repositories.RecordState) {
	fake.getStateMutex.Lock()
	defer fake.getStateMutex.Unlock()
	fake.GetStateStub = nil
	if fake.getStateReturnsOnCall == nil {
		fake.getStateReturnsOnCall = make(map[int]struct {
			result1 repositories.RecordState
		})
	}
	fake.getStateReturnsOnCall[i] = struct {
		result1 repositories.RecordState
	}{result1}
}

func (fake *RecordWithLastOperation) GetUpdatedAt() *time.Time {
	fake.getUpdatedAtMutex.Lock()
	ret, specificReturn := fake.getUpdatedAtReturnsOnCall[len(fake.getUpdatedAtArgsForCall)]
	fake.getUpdatedAtArgsForCall = append(fake.getUpdatedAtArgsForCall, struct {
	}{})
	stub := fake.GetUpdatedAtStub
	fakeReturns := fake.getUpdatedAtReturns
	fake.recordInvocation("GetUpdatedAt", []interface{}{})
	fake.getUpdatedAtMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *RecordWithLastOperation) GetUpdatedAtCallCount() int {
	fake.getUpdatedAtMutex.RLock()
	defer fake.getUpdatedAtMutex.RUnlock()
	return len(fake.getUpdatedAtArgsForCall)
}

func (fake *RecordWithLastOperation) GetUpdatedAtCalls(stub func() *time.Time) {
	fake.getUpdatedAtMutex.Lock()
	defer fake.getUpdatedAtMutex.Unlock()
	fake.GetUpdatedAtStub = stub
}

func (fake *RecordWithLastOperation) GetUpdatedAtReturns(result1 *time.Time) {
	fake.getUpdatedAtMutex.Lock()
	defer fake.getUpdatedAtMutex.Unlock()
	fake.GetUpdatedAtStub = nil
	fake.getUpdatedAtReturns = struct {
		result1 *time.Time
	}{result1}
}

func (fake *RecordWithLastOperation) GetUpdatedAtReturnsOnCall(i int, result1 *time.Time) {
	fake.getUpdatedAtMutex.Lock()
	defer fake.getUpdatedAtMutex.Unlock()
	fake.GetUpdatedAtStub = nil
	if fake.getUpdatedAtReturnsOnCall == nil {
		fake.getUpdatedAtReturnsOnCall = make(map[int]struct {
			result1 *time.Time
		})
	}
	fake.getUpdatedAtReturnsOnCall[i] = struct {
		result1 *time.Time
	}{result1}
}

func (fake *RecordWithLastOperation) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getCreatedAtMutex.RLock()
	defer fake.getCreatedAtMutex.RUnlock()
	fake.getDeletedAtMutex.RLock()
	defer fake.getDeletedAtMutex.RUnlock()
	fake.getStateMutex.RLock()
	defer fake.getStateMutex.RUnlock()
	fake.getUpdatedAtMutex.RLock()
	defer fake.getUpdatedAtMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *RecordWithLastOperation) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ presenter.RecordWithLastOperation = new(RecordWithLastOperation)
