// Code generated by counterfeiter. DO NOT EDIT.
package fake

import (
	"context"
	"sync"

	"code.cloudfoundry.org/korifi/api/authorization"
	"code.cloudfoundry.org/korifi/api/handlers"
	"code.cloudfoundry.org/korifi/api/repositories"
)

type CFServiceBindingRepository struct {
	CreateManagedServiceBindingStub        func(context.Context, authorization.Info, repositories.CreateServiceBindingMessage) (repositories.ServiceBindingRecord, error)
	createManagedServiceBindingMutex       sync.RWMutex
	createManagedServiceBindingArgsForCall []struct {
		arg1 context.Context
		arg2 authorization.Info
		arg3 repositories.CreateServiceBindingMessage
	}
	createManagedServiceBindingReturns struct {
		result1 repositories.ServiceBindingRecord
		result2 error
	}
	createManagedServiceBindingReturnsOnCall map[int]struct {
		result1 repositories.ServiceBindingRecord
		result2 error
	}
	CreateUserProvidedServiceBindingStub        func(context.Context, authorization.Info, repositories.CreateServiceBindingMessage) (repositories.ServiceBindingRecord, error)
	createUserProvidedServiceBindingMutex       sync.RWMutex
	createUserProvidedServiceBindingArgsForCall []struct {
		arg1 context.Context
		arg2 authorization.Info
		arg3 repositories.CreateServiceBindingMessage
	}
	createUserProvidedServiceBindingReturns struct {
		result1 repositories.ServiceBindingRecord
		result2 error
	}
	createUserProvidedServiceBindingReturnsOnCall map[int]struct {
		result1 repositories.ServiceBindingRecord
		result2 error
	}
	DeleteServiceBindingStub        func(context.Context, authorization.Info, string) error
	deleteServiceBindingMutex       sync.RWMutex
	deleteServiceBindingArgsForCall []struct {
		arg1 context.Context
		arg2 authorization.Info
		arg3 string
	}
	deleteServiceBindingReturns struct {
		result1 error
	}
	deleteServiceBindingReturnsOnCall map[int]struct {
		result1 error
	}
	GetServiceBindingStub        func(context.Context, authorization.Info, string) (repositories.ServiceBindingRecord, error)
	getServiceBindingMutex       sync.RWMutex
	getServiceBindingArgsForCall []struct {
		arg1 context.Context
		arg2 authorization.Info
		arg3 string
	}
	getServiceBindingReturns struct {
		result1 repositories.ServiceBindingRecord
		result2 error
	}
	getServiceBindingReturnsOnCall map[int]struct {
		result1 repositories.ServiceBindingRecord
		result2 error
	}
	ListServiceBindingsStub        func(context.Context, authorization.Info, repositories.ListServiceBindingsMessage) ([]repositories.ServiceBindingRecord, error)
	listServiceBindingsMutex       sync.RWMutex
	listServiceBindingsArgsForCall []struct {
		arg1 context.Context
		arg2 authorization.Info
		arg3 repositories.ListServiceBindingsMessage
	}
	listServiceBindingsReturns struct {
		result1 []repositories.ServiceBindingRecord
		result2 error
	}
	listServiceBindingsReturnsOnCall map[int]struct {
		result1 []repositories.ServiceBindingRecord
		result2 error
	}
	UpdateServiceBindingStub        func(context.Context, authorization.Info, repositories.UpdateServiceBindingMessage) (repositories.ServiceBindingRecord, error)
	updateServiceBindingMutex       sync.RWMutex
	updateServiceBindingArgsForCall []struct {
		arg1 context.Context
		arg2 authorization.Info
		arg3 repositories.UpdateServiceBindingMessage
	}
	updateServiceBindingReturns struct {
		result1 repositories.ServiceBindingRecord
		result2 error
	}
	updateServiceBindingReturnsOnCall map[int]struct {
		result1 repositories.ServiceBindingRecord
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *CFServiceBindingRepository) CreateManagedServiceBinding(arg1 context.Context, arg2 authorization.Info, arg3 repositories.CreateServiceBindingMessage) (repositories.ServiceBindingRecord, error) {
	fake.createManagedServiceBindingMutex.Lock()
	ret, specificReturn := fake.createManagedServiceBindingReturnsOnCall[len(fake.createManagedServiceBindingArgsForCall)]
	fake.createManagedServiceBindingArgsForCall = append(fake.createManagedServiceBindingArgsForCall, struct {
		arg1 context.Context
		arg2 authorization.Info
		arg3 repositories.CreateServiceBindingMessage
	}{arg1, arg2, arg3})
	stub := fake.CreateManagedServiceBindingStub
	fakeReturns := fake.createManagedServiceBindingReturns
	fake.recordInvocation("CreateManagedServiceBinding", []interface{}{arg1, arg2, arg3})
	fake.createManagedServiceBindingMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *CFServiceBindingRepository) CreateManagedServiceBindingCallCount() int {
	fake.createManagedServiceBindingMutex.RLock()
	defer fake.createManagedServiceBindingMutex.RUnlock()
	return len(fake.createManagedServiceBindingArgsForCall)
}

func (fake *CFServiceBindingRepository) CreateManagedServiceBindingCalls(stub func(context.Context, authorization.Info, repositories.CreateServiceBindingMessage) (repositories.ServiceBindingRecord, error)) {
	fake.createManagedServiceBindingMutex.Lock()
	defer fake.createManagedServiceBindingMutex.Unlock()
	fake.CreateManagedServiceBindingStub = stub
}

func (fake *CFServiceBindingRepository) CreateManagedServiceBindingArgsForCall(i int) (context.Context, authorization.Info, repositories.CreateServiceBindingMessage) {
	fake.createManagedServiceBindingMutex.RLock()
	defer fake.createManagedServiceBindingMutex.RUnlock()
	argsForCall := fake.createManagedServiceBindingArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *CFServiceBindingRepository) CreateManagedServiceBindingReturns(result1 repositories.ServiceBindingRecord, result2 error) {
	fake.createManagedServiceBindingMutex.Lock()
	defer fake.createManagedServiceBindingMutex.Unlock()
	fake.CreateManagedServiceBindingStub = nil
	fake.createManagedServiceBindingReturns = struct {
		result1 repositories.ServiceBindingRecord
		result2 error
	}{result1, result2}
}

func (fake *CFServiceBindingRepository) CreateManagedServiceBindingReturnsOnCall(i int, result1 repositories.ServiceBindingRecord, result2 error) {
	fake.createManagedServiceBindingMutex.Lock()
	defer fake.createManagedServiceBindingMutex.Unlock()
	fake.CreateManagedServiceBindingStub = nil
	if fake.createManagedServiceBindingReturnsOnCall == nil {
		fake.createManagedServiceBindingReturnsOnCall = make(map[int]struct {
			result1 repositories.ServiceBindingRecord
			result2 error
		})
	}
	fake.createManagedServiceBindingReturnsOnCall[i] = struct {
		result1 repositories.ServiceBindingRecord
		result2 error
	}{result1, result2}
}

func (fake *CFServiceBindingRepository) CreateUserProvidedServiceBinding(arg1 context.Context, arg2 authorization.Info, arg3 repositories.CreateServiceBindingMessage) (repositories.ServiceBindingRecord, error) {
	fake.createUserProvidedServiceBindingMutex.Lock()
	ret, specificReturn := fake.createUserProvidedServiceBindingReturnsOnCall[len(fake.createUserProvidedServiceBindingArgsForCall)]
	fake.createUserProvidedServiceBindingArgsForCall = append(fake.createUserProvidedServiceBindingArgsForCall, struct {
		arg1 context.Context
		arg2 authorization.Info
		arg3 repositories.CreateServiceBindingMessage
	}{arg1, arg2, arg3})
	stub := fake.CreateUserProvidedServiceBindingStub
	fakeReturns := fake.createUserProvidedServiceBindingReturns
	fake.recordInvocation("CreateUserProvidedServiceBinding", []interface{}{arg1, arg2, arg3})
	fake.createUserProvidedServiceBindingMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *CFServiceBindingRepository) CreateUserProvidedServiceBindingCallCount() int {
	fake.createUserProvidedServiceBindingMutex.RLock()
	defer fake.createUserProvidedServiceBindingMutex.RUnlock()
	return len(fake.createUserProvidedServiceBindingArgsForCall)
}

func (fake *CFServiceBindingRepository) CreateUserProvidedServiceBindingCalls(stub func(context.Context, authorization.Info, repositories.CreateServiceBindingMessage) (repositories.ServiceBindingRecord, error)) {
	fake.createUserProvidedServiceBindingMutex.Lock()
	defer fake.createUserProvidedServiceBindingMutex.Unlock()
	fake.CreateUserProvidedServiceBindingStub = stub
}

func (fake *CFServiceBindingRepository) CreateUserProvidedServiceBindingArgsForCall(i int) (context.Context, authorization.Info, repositories.CreateServiceBindingMessage) {
	fake.createUserProvidedServiceBindingMutex.RLock()
	defer fake.createUserProvidedServiceBindingMutex.RUnlock()
	argsForCall := fake.createUserProvidedServiceBindingArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *CFServiceBindingRepository) CreateUserProvidedServiceBindingReturns(result1 repositories.ServiceBindingRecord, result2 error) {
	fake.createUserProvidedServiceBindingMutex.Lock()
	defer fake.createUserProvidedServiceBindingMutex.Unlock()
	fake.CreateUserProvidedServiceBindingStub = nil
	fake.createUserProvidedServiceBindingReturns = struct {
		result1 repositories.ServiceBindingRecord
		result2 error
	}{result1, result2}
}

func (fake *CFServiceBindingRepository) CreateUserProvidedServiceBindingReturnsOnCall(i int, result1 repositories.ServiceBindingRecord, result2 error) {
	fake.createUserProvidedServiceBindingMutex.Lock()
	defer fake.createUserProvidedServiceBindingMutex.Unlock()
	fake.CreateUserProvidedServiceBindingStub = nil
	if fake.createUserProvidedServiceBindingReturnsOnCall == nil {
		fake.createUserProvidedServiceBindingReturnsOnCall = make(map[int]struct {
			result1 repositories.ServiceBindingRecord
			result2 error
		})
	}
	fake.createUserProvidedServiceBindingReturnsOnCall[i] = struct {
		result1 repositories.ServiceBindingRecord
		result2 error
	}{result1, result2}
}

func (fake *CFServiceBindingRepository) DeleteServiceBinding(arg1 context.Context, arg2 authorization.Info, arg3 string) error {
	fake.deleteServiceBindingMutex.Lock()
	ret, specificReturn := fake.deleteServiceBindingReturnsOnCall[len(fake.deleteServiceBindingArgsForCall)]
	fake.deleteServiceBindingArgsForCall = append(fake.deleteServiceBindingArgsForCall, struct {
		arg1 context.Context
		arg2 authorization.Info
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.DeleteServiceBindingStub
	fakeReturns := fake.deleteServiceBindingReturns
	fake.recordInvocation("DeleteServiceBinding", []interface{}{arg1, arg2, arg3})
	fake.deleteServiceBindingMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *CFServiceBindingRepository) DeleteServiceBindingCallCount() int {
	fake.deleteServiceBindingMutex.RLock()
	defer fake.deleteServiceBindingMutex.RUnlock()
	return len(fake.deleteServiceBindingArgsForCall)
}

func (fake *CFServiceBindingRepository) DeleteServiceBindingCalls(stub func(context.Context, authorization.Info, string) error) {
	fake.deleteServiceBindingMutex.Lock()
	defer fake.deleteServiceBindingMutex.Unlock()
	fake.DeleteServiceBindingStub = stub
}

func (fake *CFServiceBindingRepository) DeleteServiceBindingArgsForCall(i int) (context.Context, authorization.Info, string) {
	fake.deleteServiceBindingMutex.RLock()
	defer fake.deleteServiceBindingMutex.RUnlock()
	argsForCall := fake.deleteServiceBindingArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *CFServiceBindingRepository) DeleteServiceBindingReturns(result1 error) {
	fake.deleteServiceBindingMutex.Lock()
	defer fake.deleteServiceBindingMutex.Unlock()
	fake.DeleteServiceBindingStub = nil
	fake.deleteServiceBindingReturns = struct {
		result1 error
	}{result1}
}

func (fake *CFServiceBindingRepository) DeleteServiceBindingReturnsOnCall(i int, result1 error) {
	fake.deleteServiceBindingMutex.Lock()
	defer fake.deleteServiceBindingMutex.Unlock()
	fake.DeleteServiceBindingStub = nil
	if fake.deleteServiceBindingReturnsOnCall == nil {
		fake.deleteServiceBindingReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteServiceBindingReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *CFServiceBindingRepository) GetServiceBinding(arg1 context.Context, arg2 authorization.Info, arg3 string) (repositories.ServiceBindingRecord, error) {
	fake.getServiceBindingMutex.Lock()
	ret, specificReturn := fake.getServiceBindingReturnsOnCall[len(fake.getServiceBindingArgsForCall)]
	fake.getServiceBindingArgsForCall = append(fake.getServiceBindingArgsForCall, struct {
		arg1 context.Context
		arg2 authorization.Info
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.GetServiceBindingStub
	fakeReturns := fake.getServiceBindingReturns
	fake.recordInvocation("GetServiceBinding", []interface{}{arg1, arg2, arg3})
	fake.getServiceBindingMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *CFServiceBindingRepository) GetServiceBindingCallCount() int {
	fake.getServiceBindingMutex.RLock()
	defer fake.getServiceBindingMutex.RUnlock()
	return len(fake.getServiceBindingArgsForCall)
}

func (fake *CFServiceBindingRepository) GetServiceBindingCalls(stub func(context.Context, authorization.Info, string) (repositories.ServiceBindingRecord, error)) {
	fake.getServiceBindingMutex.Lock()
	defer fake.getServiceBindingMutex.Unlock()
	fake.GetServiceBindingStub = stub
}

func (fake *CFServiceBindingRepository) GetServiceBindingArgsForCall(i int) (context.Context, authorization.Info, string) {
	fake.getServiceBindingMutex.RLock()
	defer fake.getServiceBindingMutex.RUnlock()
	argsForCall := fake.getServiceBindingArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *CFServiceBindingRepository) GetServiceBindingReturns(result1 repositories.ServiceBindingRecord, result2 error) {
	fake.getServiceBindingMutex.Lock()
	defer fake.getServiceBindingMutex.Unlock()
	fake.GetServiceBindingStub = nil
	fake.getServiceBindingReturns = struct {
		result1 repositories.ServiceBindingRecord
		result2 error
	}{result1, result2}
}

func (fake *CFServiceBindingRepository) GetServiceBindingReturnsOnCall(i int, result1 repositories.ServiceBindingRecord, result2 error) {
	fake.getServiceBindingMutex.Lock()
	defer fake.getServiceBindingMutex.Unlock()
	fake.GetServiceBindingStub = nil
	if fake.getServiceBindingReturnsOnCall == nil {
		fake.getServiceBindingReturnsOnCall = make(map[int]struct {
			result1 repositories.ServiceBindingRecord
			result2 error
		})
	}
	fake.getServiceBindingReturnsOnCall[i] = struct {
		result1 repositories.ServiceBindingRecord
		result2 error
	}{result1, result2}
}

func (fake *CFServiceBindingRepository) ListServiceBindings(arg1 context.Context, arg2 authorization.Info, arg3 repositories.ListServiceBindingsMessage) ([]repositories.ServiceBindingRecord, error) {
	fake.listServiceBindingsMutex.Lock()
	ret, specificReturn := fake.listServiceBindingsReturnsOnCall[len(fake.listServiceBindingsArgsForCall)]
	fake.listServiceBindingsArgsForCall = append(fake.listServiceBindingsArgsForCall, struct {
		arg1 context.Context
		arg2 authorization.Info
		arg3 repositories.ListServiceBindingsMessage
	}{arg1, arg2, arg3})
	stub := fake.ListServiceBindingsStub
	fakeReturns := fake.listServiceBindingsReturns
	fake.recordInvocation("ListServiceBindings", []interface{}{arg1, arg2, arg3})
	fake.listServiceBindingsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *CFServiceBindingRepository) ListServiceBindingsCallCount() int {
	fake.listServiceBindingsMutex.RLock()
	defer fake.listServiceBindingsMutex.RUnlock()
	return len(fake.listServiceBindingsArgsForCall)
}

func (fake *CFServiceBindingRepository) ListServiceBindingsCalls(stub func(context.Context, authorization.Info, repositories.ListServiceBindingsMessage) ([]repositories.ServiceBindingRecord, error)) {
	fake.listServiceBindingsMutex.Lock()
	defer fake.listServiceBindingsMutex.Unlock()
	fake.ListServiceBindingsStub = stub
}

func (fake *CFServiceBindingRepository) ListServiceBindingsArgsForCall(i int) (context.Context, authorization.Info, repositories.ListServiceBindingsMessage) {
	fake.listServiceBindingsMutex.RLock()
	defer fake.listServiceBindingsMutex.RUnlock()
	argsForCall := fake.listServiceBindingsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *CFServiceBindingRepository) ListServiceBindingsReturns(result1 []repositories.ServiceBindingRecord, result2 error) {
	fake.listServiceBindingsMutex.Lock()
	defer fake.listServiceBindingsMutex.Unlock()
	fake.ListServiceBindingsStub = nil
	fake.listServiceBindingsReturns = struct {
		result1 []repositories.ServiceBindingRecord
		result2 error
	}{result1, result2}
}

func (fake *CFServiceBindingRepository) ListServiceBindingsReturnsOnCall(i int, result1 []repositories.ServiceBindingRecord, result2 error) {
	fake.listServiceBindingsMutex.Lock()
	defer fake.listServiceBindingsMutex.Unlock()
	fake.ListServiceBindingsStub = nil
	if fake.listServiceBindingsReturnsOnCall == nil {
		fake.listServiceBindingsReturnsOnCall = make(map[int]struct {
			result1 []repositories.ServiceBindingRecord
			result2 error
		})
	}
	fake.listServiceBindingsReturnsOnCall[i] = struct {
		result1 []repositories.ServiceBindingRecord
		result2 error
	}{result1, result2}
}

func (fake *CFServiceBindingRepository) UpdateServiceBinding(arg1 context.Context, arg2 authorization.Info, arg3 repositories.UpdateServiceBindingMessage) (repositories.ServiceBindingRecord, error) {
	fake.updateServiceBindingMutex.Lock()
	ret, specificReturn := fake.updateServiceBindingReturnsOnCall[len(fake.updateServiceBindingArgsForCall)]
	fake.updateServiceBindingArgsForCall = append(fake.updateServiceBindingArgsForCall, struct {
		arg1 context.Context
		arg2 authorization.Info
		arg3 repositories.UpdateServiceBindingMessage
	}{arg1, arg2, arg3})
	stub := fake.UpdateServiceBindingStub
	fakeReturns := fake.updateServiceBindingReturns
	fake.recordInvocation("UpdateServiceBinding", []interface{}{arg1, arg2, arg3})
	fake.updateServiceBindingMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *CFServiceBindingRepository) UpdateServiceBindingCallCount() int {
	fake.updateServiceBindingMutex.RLock()
	defer fake.updateServiceBindingMutex.RUnlock()
	return len(fake.updateServiceBindingArgsForCall)
}

func (fake *CFServiceBindingRepository) UpdateServiceBindingCalls(stub func(context.Context, authorization.Info, repositories.UpdateServiceBindingMessage) (repositories.ServiceBindingRecord, error)) {
	fake.updateServiceBindingMutex.Lock()
	defer fake.updateServiceBindingMutex.Unlock()
	fake.UpdateServiceBindingStub = stub
}

func (fake *CFServiceBindingRepository) UpdateServiceBindingArgsForCall(i int) (context.Context, authorization.Info, repositories.UpdateServiceBindingMessage) {
	fake.updateServiceBindingMutex.RLock()
	defer fake.updateServiceBindingMutex.RUnlock()
	argsForCall := fake.updateServiceBindingArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *CFServiceBindingRepository) UpdateServiceBindingReturns(result1 repositories.ServiceBindingRecord, result2 error) {
	fake.updateServiceBindingMutex.Lock()
	defer fake.updateServiceBindingMutex.Unlock()
	fake.UpdateServiceBindingStub = nil
	fake.updateServiceBindingReturns = struct {
		result1 repositories.ServiceBindingRecord
		result2 error
	}{result1, result2}
}

func (fake *CFServiceBindingRepository) UpdateServiceBindingReturnsOnCall(i int, result1 repositories.ServiceBindingRecord, result2 error) {
	fake.updateServiceBindingMutex.Lock()
	defer fake.updateServiceBindingMutex.Unlock()
	fake.UpdateServiceBindingStub = nil
	if fake.updateServiceBindingReturnsOnCall == nil {
		fake.updateServiceBindingReturnsOnCall = make(map[int]struct {
			result1 repositories.ServiceBindingRecord
			result2 error
		})
	}
	fake.updateServiceBindingReturnsOnCall[i] = struct {
		result1 repositories.ServiceBindingRecord
		result2 error
	}{result1, result2}
}

func (fake *CFServiceBindingRepository) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createManagedServiceBindingMutex.RLock()
	defer fake.createManagedServiceBindingMutex.RUnlock()
	fake.createUserProvidedServiceBindingMutex.RLock()
	defer fake.createUserProvidedServiceBindingMutex.RUnlock()
	fake.deleteServiceBindingMutex.RLock()
	defer fake.deleteServiceBindingMutex.RUnlock()
	fake.getServiceBindingMutex.RLock()
	defer fake.getServiceBindingMutex.RUnlock()
	fake.listServiceBindingsMutex.RLock()
	defer fake.listServiceBindingsMutex.RUnlock()
	fake.updateServiceBindingMutex.RLock()
	defer fake.updateServiceBindingMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *CFServiceBindingRepository) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ handlers.CFServiceBindingRepository = new(CFServiceBindingRepository)
